// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWAQNuDiPNsllJi-AKfHusQ-f2CXvil1A',
    appId: '1:584458157661:web:e497c905524b0feb9b17b4',
    messagingSenderId: '584458157661',
    projectId: 'chatappflutter-cf51e',
    authDomain: 'chatappflutter-cf51e.firebaseapp.com',
    storageBucket: 'chatappflutter-cf51e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtpdgbtu7umD1lGNTqvEKFSuV3WbpdPUM',
    appId: '1:584458157661:android:64d7181e70c8652d9b17b4',
    messagingSenderId: '584458157661',
    projectId: 'chatappflutter-cf51e',
    storageBucket: 'chatappflutter-cf51e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmJ1vMVYc31xGRupSsJwBjp3JdWtZGHZM',
    appId: '1:584458157661:ios:5232b5518177dba39b17b4',
    messagingSenderId: '584458157661',
    projectId: 'chatappflutter-cf51e',
    storageBucket: 'chatappflutter-cf51e.appspot.com',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmJ1vMVYc31xGRupSsJwBjp3JdWtZGHZM',
    appId: '1:584458157661:ios:cef1aa236d0e2ff39b17b4',
    messagingSenderId: '584458157661',
    projectId: 'chatappflutter-cf51e',
    storageBucket: 'chatappflutter-cf51e.appspot.com',
    iosBundleId: 'com.example.chatappFirebase.RunnerTests',
  );
}
